# Generated by Django 5.1.3 on 2024-11-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskFlow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
    ]
