# Generated by Django 5.1.3 on 2024-11-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskFlow', '0002_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='desc',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
